export enum DL_ERRORS {
    FATAL_ERROR,
    ALREADY_EXIST,
    NOT_EXIST
}
export const ERROR_MESSAGES_MAPPER = [];
ERROR_MESSAGES_MAPPER[DL_ERRORS.FATAL_ERROR] = { message: 'FATAL_ERROR', code: 500 };
ERROR_MESSAGES_MAPPER[DL_ERRORS.ALREADY_EXIST] = { message: 'ALREADY_EXIST', code: 604 };
ERROR_MESSAGES_MAPPER[DL_ERRORS.NOT_EXIST] = { message: 'NOT_EXIST', code: 605 };
