export enum DL_ERRORS {
    FATAL_ERROR,
    ALREADY_EXIST,
    NOT_EXIST,
    NO_RESULTS,
    NOT_CREATED,
    MATCH_ERROR,
}
export const DL_ERROR_MESSAGES_MAPPER = [];
DL_ERROR_MESSAGES_MAPPER[DL_ERRORS.FATAL_ERROR] = { message: 'FATAL_ERROR', code: 500 };
DL_ERROR_MESSAGES_MAPPER[DL_ERRORS.ALREADY_EXIST] = { message: 'ALREADY_EXIST', code: 604 };
DL_ERROR_MESSAGES_MAPPER[DL_ERRORS.NOT_EXIST] = { message: 'NOT_EXIST', code: 605 };
DL_ERROR_MESSAGES_MAPPER[DL_ERRORS.NO_RESULTS] = { message: 'NO_RESULTS', code: 607 };
DL_ERROR_MESSAGES_MAPPER[DL_ERRORS.NOT_CREATED] = { message: 'NOT_CREATED', code: 608 };
DL_ERROR_MESSAGES_MAPPER[DL_ERRORS.MATCH_ERROR] = { message: 'MATCH_ERROR', code: 609 };
